### ISSUE TITLE
mfcc 

### ISSUE THREAD

**Issue by wafer9** [lovemefan/telespeech-asr-python#2]
https://github.com/lovemefan/telespeech-asr-python/blob/c90966e55cb0fd4dd218c490d1335df60c876838/telespeechasr/onnx/onnx_infer.py#L207

samples *= 372768 ，这个值应该是32768吧？

**Comment by lovemefan** [comment]
> https://github.com/lovemefan/telespeech-asr-python/blob/c90966e55cb0fd4dd218c490d1335df60c876838/telespeechasr/onnx/onnx_infer.py#L207
> 
> samples *= 372768 ，这个值应该是32768吧？

是的😂，你是对的。打错了，没发现
