### ISSUE TITLE
是否有计划增加finetune功能？

### ISSUE THREAD

**Issue by ffffuturexu** [lovemefan/telespeech-asr-python#6]
感谢发布该项目，原项目的kaldi配置确实十分头疼

看到目前只支持模型inference，想请问是否考虑增加finetune功能？

**Comment by lovemefan** [comment]
以我个人经验，自己手写的训练效果不如fairseq，而且有一定工作量，所以不太考虑增加finetune。可以在原项目中将预处理使用kaldi的处理部分用kaldifest库替换掉，继续使用faireseq微调
