### ISSUE TITLE
请问如何转换官方checkpoints

### ISSUE THREAD

**Issue by EBGU** [lovemefan/telespeech-asr-python#7]
您好！
我想load预训练的pretrain_large checkpoints来抽取表示，请问怎么把官方的checkpoints转换成您这个可以使用的呀？
谢谢！

**Comment by lovemefan** [comment]
> 您好！ 我想load预训练的pretrain_large checkpoints来抽取表示，请问怎么把官方的checkpoints转换成您这个可以使用的呀？ 谢谢！

你好，回复晚了。新增一个转换脚本 https://github.com/lovemefan/telespeech-asr-python/blob/main/telespeechasr/torch/utils/convert_fairseq_checkpoint.py 用于转换原版checkpoint

使用方式如下
```python
python convert_pt.py --input finetune_large_kespeech.pt --output torch_checkpoint.pt
```

**Comment by EBGU** [comment]
谢谢您！

**Comment by lovemefan** [comment]
哦对了， pretrain模型是没有 w2v_encoder.proj.weight 和w2v_encoder.proj.bias 线性层的，而且我发现pretrain和finetune的键值也不一样，如果需要转换pretrain model 这个脚本是不行的，只能转finetune模型。后续有需求请再次留言
