### ISSUE TITLE
关于自己训练的模型推理乱码问题

### ISSUE THREAD

**Issue by rainskyfyy** [lovemefan/telespeech-asr-python#8]
您好，我自己根据[TeleSpeech-ASR](https://github.com/Tele-AI/TeleSpeech-ASR)项目训练了一版模型，在TeleSpeech-ASR项目的decode.sh脚本下推理时可以正常推理，但是用您这边代码进行推理时就出现一系列乱码，请问是哪里需要适配吗？
vocab.json文件我根据自己训练的模型的字典构造了新的，模型是用telespeechasr/onnx/onnx_export.py脚本转出来的。

**Comment by lovemefan** [comment]
> 您好，我自己根据[TeleSpeech-ASR](https://github.com/Tele-AI/TeleSpeech-ASR)项目训练了一版模型，在TeleSpeech-ASR项目的decode.sh脚本下推理时可以正常推理，但是用您这边代码进行推理时就出现一系列乱码，请问是哪里需要适配吗？ vocab.json文件我根据自己训练的模型的字典构造了新的，模型是用telespeechasr/onnx/onnx.export.py脚本转出来的。

能否分享一下识别出来的token id 的列表，确认一下是否是解码问题

**Comment by rainskyfyy** [comment]
tokens:[5324 7243 5324 5324 7243 5324 7243 1092 5324 7243 1092 5324 5324 7243
 5324 5324 5324 4660 5324 1935 1092 2697 5324 4660 5324 4660 5324 5540
 5324 4660 4660 7243 7243  741 1935 7243 1092 2697 1935 3996 5324 5324
 1935 5324 5324 2697 5324 4660 5324 1015 5324 5324 1935 ...]类似这样的

**Comment by lovemefan** [comment]
> tokens:[5324 7243 5324 5324 7243 5324 7243 1092 5324 7243 1092 5324 5324 7243 5324 5324 5324 4660 5324 1935 1092 2697 5324 4660 5324 4660 5324 5540 5324 4660 4660 7243 7243 741 1935 7243 1092 2697 1935 3996 5324 5324 1935 5324 5324 2697 5324 4660 5324 1015 5324 5324 1935 ...]类似这样的

目前信息不太多，问题不太好排查， 请问是使用下面的转换脚本 convert_fairseq_checkpoint.py 转换的checkpoint吗？torch上推理会不会乱码？

```bash
python telespeechasr/torch/utils/convert_fairseq_checkpoint.py --input /path/finetune_large_kespeech.pt --output /path/torch_checkpoint.pt
```

**Comment by rainskyfyy** [comment]
转换脚本用的这个：telespeechasr/onnx/onnx_export.py，目前因为环境问题还没有在torch上测过

**Comment by lovemefan** [comment]
> 转换脚本用的这个：telespeechasr/onnx/onnx.export.py，目前因为环境问题还没有在torch上测过

fairseq训练出的checkpoint先用convert_fairseq_checkpoint.py转换成本项目的结构，然后接着用onnx_export.py转换成onnx模型试试

**Comment by rainskyfyy** [comment]
您是说fairseq2/models/utils/checkpoint.py里面的convert_fairseq_checkpoint函数吗？

**Comment by lovemefan** [comment]
> 您是说fairseq2/models/utils/checkpoint.py里面的convert_fairseq_checkpoint函数吗？

这个 https://github.com/lovemefan/telespeech-asr-python/blob/main/telespeechasr/torch/utils/convert_fairseq_checkpoint.py

**Comment by rainskyfyy** [comment]
感谢！问题已经解决了（convert_fairseq_checkpoint.py这个脚本我更新分支才看到，哈哈）
但是还有一点要说明一下，在用onnx_export.py转出onnx模型时，因为自己训练的模型换了字典，所以在创建模型时需要手动指定一下vocab_size，代码示例：
```
model = Data2VecMultiModel(vocab_size=6682)
```
这一点您README文档里面好像没有提到

**Comment by lovemefan** [comment]
> 感谢！问题已经解决了（convert_fairseq_checkpoint.py这个脚本我更新分支才看到，哈哈） 但是还有一点要说明一下，在用onnx_export.py转出onnx模型时，因为自己训练的模型换了字典，所以在创建模型时需要手动指定一下vocab_size，代码示例：
> 
> ```
> model = Data2VecMultiModel(vocab_size=6682)
> ```
> 
> 这一点您README文档里面好像没有提到

👏👏👏  很棒，我更新一下
